services:
  - type: web
    name: brevly-server
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./server/Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Neon Database
      - key: DATABASE_URL
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        value: 5432
      # Cloudflare R2
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_ACCESS_KEY_ID
        sync: false
      - key: CLOUDFLARE_SECRET_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_BUCKET
        sync: false
      - key: CLOUDFLARE_PUBLIC_URL
        sync: false

databases:
  - name: brevly-db
    databaseName: brevly
    user: brevly_user
    plan: starter
    region: oregon 