name: Deploy

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches: [master, main]

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install
          cd server && pnpm install
          cd ../web && pnpm install

      - name: Build applications
        run: |
          cd server && pnpm run build
          cd ../web && pnpm run build

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Adicione aqui os comandos para deploy em staging
          # Exemplo: Railway, Vercel, etc.
        env:
          NODE_ENV: staging
          # Adicione suas variáveis de ambiente de staging

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}
    needs: deploy-staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install
          cd server && pnpm install
          cd ../web && pnpm install

      - name: Build applications
        run: |
          cd server && pnpm run build
          cd ../web && pnpm run build

      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Adicione aqui os comandos para deploy em produção
          # Exemplo: Railway, Vercel, etc.
        env:
          NODE_ENV: production
          # Adicione suas variáveis de ambiente de produção

      - name: Notify deployment success
        run: |
          echo "Production deployment completed successfully!"
          # Aqui você pode adicionar notificações (Slack, Discord, etc.) 